apiVersion: cis.f5.com/v1
kind: IngressLink
metadata:
  labels:
    app.kubernetes.io/name: k8s-bigip-ctlr
    app.kubernetes.io/managed-by: kustomize
  name: ingresslink-sample
spec:
  # TODO(user): Add fields here
